### ISSUE TITLE
انت بتحضّر عفاريت؟

### ISSUE THREAD

**Issue by eawd** [SuperKareem/triton-500-opencore--pt515-51-#1]
<div dir="rtl">
صباح الخير

انت بتحاول تحضّر عفاريت؟ ولو كدة هل في أي progress أو محتاج أي مُساعدة؟

شكرًا
</div>

**Comment by SuperKareem** [comment]
la yasta msh 3afaret wala 7aga :D da EFI boot bta3 el hackintosh 3shan el laptop beta3y 👯

**Comment by eawd** [comment]
I don't care what you say I choose to believe what I believe 😂

**Comment by SuperKareem** [comment]
ya3ne afta7 el issue tany 😅  ?

**Comment by eawd** [comment]
لا , خلاص , بس لو لقيت عفاريت حطها في الـ README 😇

**Comment by Radi-Mortada** [comment]
I got this unhandled exception, please help

UnhandledException: 3afreet.3aoo is not a function.

**Comment by eawd** [comment]
@Radi-Mortada You can't start a variable name with a digit, can you try changing that to `👻.wooo();`?
